spring:
  application:
    name: sample-projectserver
  server:
    error:
      include-message: always
      include-binding-errors: always

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin@123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true
    show-sql: true
---
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

sentry:
  dsn: https://4dfee89a1384bb26bfe2ac25df9e1a9f@o4506523734900736.ingest.sentry.io/4506523754758144
---
rsa:
  private-key: classpath:private-key.pem
  public-key: classpath:public-key.pem

---
spring:
  cache:
    type: redis
    redis:
      time-to-live: PT2M
  data:
    redis:
      host: localhost
      port: 6379
      password: Redis@123

---
spring:
  data:
    mongodb:
      host: "localhost"
      port: 27017
      username: "user" # use have to create this user
      password: "User123"
      database: "sample_db"
