spring:
  application:
    name: sample-project
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin@123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true
    show-sql: true