scrape_configs:
  - job_name: 'Spring Boot Application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      -
        targets: ['172.17.0.1:8080']
        labels:
          application: 'My Spring Boot Application'
